### ISSUE TITLE
Add support for Gymnasium v0.27.0

### ISSUE THREAD

**Issue by pseudo-rnd-thoughts** [conda-forge/gymnasium-feedstock#1]
### Comment:

Hi, Im the project manager of Gymnasium. 
We would be interested in the conda feedstock including the optional installs, in a similar way to the conda gym optional installs.
Additionally, could we update the project to Gymnasium v0.27.0 which was released a couple of days ago

**Comment by thewchan** [comment]
@pseudo-rnd-thoughts Usually the bots should detect upstream changes but in some cases it fails to do so. I will take a look.

As for optional installs, that is doable but it's a heavily lift, I can see if I can work on that moving forward. Are you and others interested in becoming maintainers of this feedstock as well?

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for doing that. Yes, could you be able to add myself, @jkterry1 as authors to the repo

**Comment by h-vetinari** [comment]
I removed the "optional dependencies" part from the title, which is now solved (for the state of 0.26.3 at least, new dependencies in 0.27 notwithstanding, see e.g. #8). PRs for 0.27 are obviously welcome! :)

**Comment by jjyyxx** [comment]
Coming from https://github.com/Farama-Foundation/Gymnasium/issues/5, adding `jax-jumpy` and `typing_extensions` to runtime dependencies of `gymnasium` in #23 seems to fix the build.

**Comment by jjyyxx** [comment]
@h-vetinari Maybe #24 solves this issue?

**Comment by h-vetinari** [comment]
> @h-vetinari Maybe #24 solves this issue?

Yes, this issue can be closed
